services:
  postgres:
    image: postgres:16
    container_name: surf-school-postgres

    environment:
      POSTGRES_USER: surf_school
      POSTGRES_PASSWORD: surf_school
      POSTGRES_DB: surf_school

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data: